### ISSUE TITLE
Write an explanatory blog

### ISSUE THREAD

**Issue by Rishit-dagli** [Rishit-dagli/Greenathon-Plant-AI#29]
I think it is a great idea to write a small explanatory blog about how we built this project.

---

cc: @mindninjaX @RuchaYagnik

**Comment by mindninjaX** [comment]
That sounds like a great idea! I have already written the frontend and UI/UX part. It's a couple of paragraphs & isn't much in detail.

Main things I have tried to cover why and how we made our design choices and our motives behind them.

**Comment by Rishit-dagli** [comment]
> That sounds like a great idea! I have already written the frontend and UI/UX part. It's a couple of paragraphs & isn't much in detail.
> 
> Main things I have tried to cover why and how we made our design choices and our motives behind them.

That makes sense, Thanks for adding that!
